version: 1.1.0.{build}
configuration:
- Debug
- Release
platform: Any CPU
branches:
  only:
  - master
build:
  parallel: true
  verbosity: minimal
before_build:
- nuget restore RedisAspNetProviders.sln
test:
  assemblies: '**\*.Tests.dll'
before_test:
- cd packages\Redis-64.2.8.19\
- .\redis-server.exe --service-install
- .\redis-server.exe --service-start
- cd ..\..
after_test:
- cd packages\Redis-64.2.8.19\
- .\redis-server.exe --service-stop
- .\redis-server.exe --service-uninstall
- cd ..\..